### ISSUE TITLE
Crash when showing on multiple displays

### ISSUE THREAD

**Issue by kuwii** [dremin/RetroBar#500]
When selecting `Show on multiple displays` in `Properties`, the program will crash with the following message:

![image](https://user-images.githubusercontent.com/10705175/210921265-f1417c06-3203-4a5a-be35-37f81ac7f330.png)

Related log seems to be:

```
[1/6/2023 11:04:56 AM] Error: Would you like to restart RetroBar?

Please submit a bug report with a screenshot of this error. Thanks! 
Message: Not enough quota is available to process this command.
Target Site: Void UpdateWindowSettings(Boolean, System.Nullable`1[System.Windows.Media.Composition.DUCE+ChannelSet])
Version: 1.11.15.3343

   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	:::Exception Details:::
	System.ComponentModel.Win32Exception (1816): Not enough quota is available to process this command.
	   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
	   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
	   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
	   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

User config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <RetroBar.Properties.Settings>
            <setting name="IsFirstRun" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="ShowMultiMon" serializeAs="String">
                <value>True</value>
            </setting>
        </RetroBar.Properties.Settings>
    </userSettings>
</configuration>
```

**Comment by kuwii** [comment]
Seems duplicate with #456
