### ISSUE TITLE
Crashes in dual-monitor setups when opened before extending displays

### ISSUE THREAD

**Issue by xoascf** [dremin/RetroBar#75]
OS: Windows 10 21H1 x64
RetroBar version: 1.4 ([106b961](https://github.com/dremin/RetroBar/commit/106b9613ebb05de0bce88c57806adb84226e063b))

RetroBar crashes when it is already open and the user wants to "Extend these displays" (from 1 to 2 screens).
Windows XP normally renders the taskbar only on the first screen, so keep that behaviour or make it configurable to use a user-selected screen.

**Comment by dremin** [comment]
I haven't been able to reproduce this. Are you able to catch it while debugging?

**Comment by xoascf** [comment]
> 
> 
> I haven't been able to reproduce this. Are you able to catch it while debugging?

It seemed to be working, until I switched from PC screen only, and then from Duplicate to Extend, and the error appeared (line 63 of Taskbar.xaml.cs)
Details:
```
System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=Not enough quota is available to process this command.
  Source=PresentationCore
  StackTrace:
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by dremin** [comment]
What is the resolution and scaling set to on each display?

**Comment by xoascf** [comment]
1080p (1920x1080) on both displays (monitor and laptop screen).

**Comment by xoascf** [comment]
It seems that this problem has not reoccurred for some time now, something unknown to me must have fixed this...
