### ISSUE TITLE
Error when opening properties

### ISSUE THREAD

**Issue by SMUsamaShah** [dremin/RetroBar#751]
Copied this error from the error dialog by clicking its titlebar and then `Ctrl + C`.

```
---------------------------
RetroBar Error
---------------------------
Would you like to restart RetroBar?



Please submit a bug report with a screenshot of this error. Thanks! 

Message: Could not find a part of the path 'C:\Users\my_name\AppData\Local\Temp\.net\RetroBar\wsRNoIvdFCuLybyiMz2SXe6oa2qQ48w=\Languages'.

Target Site: IntPtr CreateDirectoryHandle(System.String, Boolean)

Version: 1.14.11.42314



   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)

   at System.IO.Enumeration.FileSystemEnumerator`1.Init()

   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)

   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)

   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)

   at System.IO.Directory.InternalEnumeratePaths(String path, String se...
---------------------------
Yes   No   
---------------------------
```

**Comment by dremin** [comment]
This can happen when the exe does not get decompressed by .NET correctly. Trying again with the latest version should resolve this.

**Comment by dremin** [comment]
This is addressed in the latest release via the installer.
